version: '2'
services:
  app:
    image: golang:1.12.5-alpine3.9
    ports:
      - "8284:51000"
    volumes:
      - .:/go/src/github.com/ClementTeyssa/3PJT-DNode/
    working_dir: /go/src/github.com/ClementTeyssa/3PJT-DNode/
    command: go run dnode.go
    labels:
      - "traefik.docker.network=web"
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:3pjt-dnode.infux.fr"
      - "traefikbasic.port=8284"
    networks:
      - web
      - default
networks:
  web:
    external: true